// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbeuwingqwmsjdfnwvel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZXV3aW5ncXdtc2pkZm53dmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTYyMzQsImV4cCI6MjA2Njk5MjIzNH0._19nMaKjXr3-_M_tu0CEkwfQdDm0CEl_kM9GyME6G1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});